# Generated by Django 3.0.5 on 2020-04-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagens_for_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('position', models.IntegerField()),
                ('imagetitle', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_post', models.CharField(choices=[('simplePost', 'Post Simples'), ('postQuote', 'Citação na Tela Inicial'), ('postAudio', 'Post com Audio'), ('postVideo', 'Post com Video'), ('postMultipleImagens', 'Post com Multiplas Imagens in Carrousel')], max_length=20, verbose_name='Tipo de Post')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('date_of_publication', models.DateField(auto_now_add=True, verbose_name='Data de Publicacao')),
                ('modified_in', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificacao')),
                ('label', models.SlugField(verbose_name='Url')),
                ('summary_post', models.TextField(verbose_name='Resumo do Post')),
                ('text_no_formated', models.TextField(verbose_name='Texto sem formatação')),
                ('text_html', models.TextField(verbose_name='Texto em Html')),
                ('imagelist', models.ManyToManyField(to='my_blog.imagens_for_post')),
            ],
            options={
                'ordering': ['date_of_publication'],
            },
        ),
    ]
