# Generated by Django 3.0.5 on 2020-04-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_thumb',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagem da Thumb'),
        ),
    ]
