# Generated by Django 3.0.5 on 2020-04-21 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_auto_20200421_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('contact_Site', models.URLField(blank=True, null=True, verbose_name='Site pessoal')),
                ('contact_Facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('contact_Twiter', models.URLField(blank=True, null=True, verbose_name='Twiter')),
                ('contact_Instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('contact_GitHub', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('contact_Linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_blog.Author'),
        ),
    ]
