# Generated by Django 3.0.5 on 2020-04-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_author_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='firt_Name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_Name',
            field=models.CharField(max_length=50, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_blog.Author'),
        ),
    ]
