# Generated by Django 3.0.5 on 2020-04-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_auto_20200421_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firt_Name',
            field=models.CharField(max_length=10, null=True, verbose_name='Nome'),
        ),
    ]
