# Generated by Django 3.0.5 on 2020-04-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0007_auto_20200421_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firt_Name',
            new_name='first_Name',
        ),
    ]
