# Generated by Django 3.0.5 on 2020-04-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0008_auto_20200421_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_no_formated',
        ),
    ]
