# Generated by Django 3.0.5 on 2020-04-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0009_remove_post_text_no_formated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome da Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categorys',
            field=models.ManyToManyField(blank=True, to='my_blog.Category'),
        ),
    ]
