# Generated by Django 3.0.5 on 2020-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0010_auto_20200422_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_of_publication']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_publication',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicacao'),
        ),
    ]
