# Generated by Django 3.0.5 on 2020-04-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0011_auto_20200422_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_in_quote',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Autor da citação'),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.SlugField(blank=True, unique=True, verbose_name='Url'),
        ),
    ]
