# Generated by Django 3.0.5 on 2020-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0013_auto_20200424_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postquote',
            name='quote',
            field=models.CharField(max_length=244, unique=True, verbose_name='Citação'),
        ),
    ]
